"""
This type stub file was generated by pyright.
"""

# from .base_classes import Baseevents, Baserequests, ClassFactory
from .core import obsws

"""
Python library to communicate with an obs-websocket server.
"""
events = ...
requests = ...
__all__ = ["obsws", "events", "requests"]
VERSION = ...
